<?php

namespace AppBundle\Repository;

/**
 * ChamadosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChamadosRepository extends \Doctrine\ORM\EntityRepository
{
}
