<?php

namespace AppBundle\Repository;

/**
 * ClientesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientesRepository extends \Doctrine\ORM\EntityRepository
{
}
