<?php

namespace AppBundle\Repository;

/**
 * PedidosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PedidosRepository extends \Doctrine\ORM\EntityRepository
{
}
